Repository kresult/kresult, pull requests merged in 2024-10, with the labels that each got.

#20 Feature/apache license
  LICENSE
  README.md
Labels: documentation

#18 Feature/readme-improvement-0.4.x
  README.md
Labels: documentation

#22 Bugfix/code smells 0.4.0
  gradle/libs.versions.toml
  integrations/kresult-arrow/src/commonTest/kotlin/io/kresult/integration/arrow/ArrowExtensionsTest.kt
  libs/kresult-core/src/commonMain/kotlin/io/kresult/core/GenericTypeExtensions.kt
  libs/kresult-core/src/commonMain/kotlin/io/kresult/core/KResult.kt
  libs/kresult-core/src/commonMain/kotlin/io/kresult/core/KResultExtensions.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/FailureTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/FailureWithValueTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/GenericTypeExtensionsTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/KResultExtensionsTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/KResultTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/SuccessTest.kt
Labels: enhancement

#23 Feature/improved gradle build setup
  .codacy.yml
  .editorconfig
  .github/workflows/build.yml
  build.gradle.kts
  convention-plugins/build.gradle.kts
  convention-plugins/settings.gradle.kts
  convention-plugins/src/main/kotlin/kresult.code-quality.gradle.kts
  convention-plugins/src/main/kotlin/kresult.docs.gradle.kts
  convention-plugins/src/main/kotlin/kresult.maven-publish.gradle.kts
  examples/build.gradle.kts
  gradle/libs.versions.toml
  integrations/build.gradle.kts
  integrations/kresult-arrow/README.md
  integrations/kresult-arrow/build.gradle.kts
  integrations/kresult-arrow/src/commonMain/kotlin/io/kresult/integration/arrow/ArrowExtensions.kt
  integrations/kresult-arrow/src/commonTest/kotlin/io/kresult/integration/arrow/ArrowExtensionsTest.kt
  libs/build.gradle.kts
  libs/kresult-core/README.md
  libs/kresult-core/build.gradle.kts
  libs/kresult-core/src/commonMain/kotlin/io/kresult/core/GenericTypeExtensions.kt
  libs/kresult-core/src/commonMain/kotlin/io/kresult/core/KResult.kt
  libs/kresult-core/src/commonMain/kotlin/io/kresult/core/KResultExtensions.kt
  libs/kresult-core/src/commonMain/kotlin/io/kresult/core/MultiErrorKResult.kt
  libs/kresult-core/src/commonMain/kotlin/io/kresult/core/MultiValueKResult.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/FailureTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/FailureWithValueTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/GenericTypeExtensionsTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/KResultExtensionsTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/KResultTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/core/SuccessTest.kt
  libs/kresult-core/src/commonTest/kotlin/io/kresult/it/SimpleIntegrationTest.kt
  libs/kresult-java/README.md
  libs/kresult-java/build.gradle.kts
  libs/kresult-java/src/jvmMain/kotlin/io/kresult/java/OptionalExtension.kt
  libs/kresult-java/src/jvmTest/kotlin/io/kresult/java/OptionalExtensionTest.kt
  libs/kresult-problem/README.md
  libs/kresult-problem/build.gradle.kts
  libs/kresult-problem/src/commonMain/kotlin/io/kresult/problem/Problem.kt
  libs/kresult-problem/src/commonMain/kotlin/io/kresult/problem/ProblemDefinition.kt
  libs/kresult-problem/src/commonTest/kotlin/io/kresult/problem/ProblemTest.kt
  libs/kresult-problem/src/commonTest/kotlin/io/kresult/problem/ProblemTest4xx.kt
  libs/kresult-problem/src/commonTest/kotlin/io/kresult/problem/ProblemTest5xx.kt
  libs/kresult-problem/src/commonTest/kotlin/io/kresult/problem/ProblemTest7xx.kt
  settings.gradle.kts
Labels: devops
